# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fc75f955d8e504434ec750140da4a4e617412377a76fa6f66d1d5c441fb9b8d2ee5101b2ac409bcf01be139812bf6acb2286f57495b44cb831624ecfebc8356

test:
  secret_key_base: 15e023335601682a8edb24f2d3ca4fe3aea7810cd8e0e5e6c030a71545d0d77922873290b1041667032e6b3609057cdc3af14c51a71be9166655055901838252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
